# Generated by Django 2.0.5 on 2018-11-11 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181110_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='attendees_range',
            new_name='attendees',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_date',
            new_name='event_end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_time',
            new_name='event_start',
        ),
    ]
